[tool.poetry]
name = "ncmrobot"
version = "0.1.0"
description = ""
authors = ["Aiden Huang <ahuang9688@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
PyYAML = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
